-- Auto-generated by midi.py
-- Made by Fxke
-- Source : luciddreams.mid
-- BPM    : 84  |  Bars: 16  |  Grid: 16 cells/bar

local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local MELODY_SAMPLE  = 200   -- 61=Piano-C  178=Bell Bright
local BASS_SAMPLE    = 116     -- 1=Bass Synth
local KICK_BASIC     = 17
local SNARE_CLEAN    = 4
local HIHAT_METALLIC = 15

local melodyBars = {
    -- Bar 1
    { {pitch=-10,cells={16}}, {pitch=-8,cells={8}}, {pitch=-4,cells={11}}, {pitch=-3,cells={3}}, {pitch=1,cells={4,12}}, {pitch=8,cells={9,14}}, {pitch=9,cells={1,6}} },
    -- Bar 2
    { {pitch=-10,cells={3,8}}, {pitch=-1,cells={4,11}}, {pitch=5,cells={13}}, {pitch=6,cells={1,6,9}} },
    -- Bar 3
    { {pitch=-10,cells={16}}, {pitch=-8,cells={8}}, {pitch=-6,cells={3}}, {pitch=-4,cells={11}}, {pitch=1,cells={12}}, {pitch=2,cells={4}}, {pitch=8,cells={9,14}}, {pitch=9,cells={1,6}} },
    -- Bar 4
    { {pitch=-11,cells={16}}, {pitch=-10,cells={3,8}}, {pitch=-1,cells={4,11}}, {pitch=5,cells={13}}, {pitch=6,cells={1,6,9}} },
    -- Bar 5
    { {pitch=-15,cells={16}}, {pitch=-10,cells={1}}, {pitch=-1,cells={3,6,13}}, {pitch=6,cells={4,11}}, {pitch=9,cells={8}} },
    -- Bar 6
    { {pitch=-13,cells={1}}, {pitch=-11,cells={9}}, {pitch=-10,cells={7}}, {pitch=-6,cells={4}}, {pitch=1,cells={11}}, {pitch=5,cells={13}}, {pitch=8,cells={12}} },
    -- Bar 7
    { {pitch=-11,cells={9}}, {pitch=-4,cells={1}}, {pitch=1,cells={9,12}}, {pitch=2,cells={7}}, {pitch=4,cells={4}}, {pitch=6,cells={1}} },
    -- Bar 8
    { {pitch=-6,cells={1}}, {pitch=-4,cells={1}}, {pitch=-1,cells={2}}, {pitch=1,cells={3}} },
    -- Bar 9
    { {pitch=-10,cells={16}}, {pitch=-8,cells={8}}, {pitch=-4,cells={11}}, {pitch=-3,cells={3}}, {pitch=1,cells={4,12}}, {pitch=8,cells={9,14}}, {pitch=9,cells={1,6}} },
    -- Bar 10
    { {pitch=-10,cells={3,8}}, {pitch=-1,cells={4,11}}, {pitch=5,cells={13}}, {pitch=6,cells={1,6,9}} },
    -- Bar 11
    { {pitch=-10,cells={16}}, {pitch=-8,cells={8}}, {pitch=-6,cells={3}}, {pitch=-4,cells={11}}, {pitch=1,cells={12}}, {pitch=2,cells={4}}, {pitch=8,cells={9,14}}, {pitch=9,cells={1,6}} },
    -- Bar 12
    { {pitch=-11,cells={16}}, {pitch=-10,cells={3,8}}, {pitch=-1,cells={4,11}}, {pitch=5,cells={13}}, {pitch=6,cells={1,6,9}} },
    -- Bar 13
    { {pitch=-15,cells={16}}, {pitch=-10,cells={1}}, {pitch=-1,cells={3,6,13}}, {pitch=6,cells={4,11}}, {pitch=9,cells={8}} },
    -- Bar 14
    { {pitch=-13,cells={1}}, {pitch=-11,cells={9}}, {pitch=-10,cells={7}}, {pitch=-6,cells={4}}, {pitch=1,cells={11}}, {pitch=5,cells={13}}, {pitch=8,cells={12}} },
    -- Bar 15
    { {pitch=-11,cells={9}}, {pitch=-4,cells={1}}, {pitch=1,cells={9,12}}, {pitch=2,cells={7}}, {pitch=4,cells={4}}, {pitch=6,cells={1}} },
    -- Bar 16
    { {pitch=-6,cells={1}}, {pitch=-4,cells={1}}, {pitch=-1,cells={2}}, {pitch=1,cells={3}} },
}

local bassBars = {
    -- Bar 1
    {},  -- rest bar
    -- Bar 2
    {},  -- rest bar
    -- Bar 3
    {},  -- rest bar
    -- Bar 4
    {},  -- rest bar
    -- Bar 5
    {},  -- rest bar
    -- Bar 6
    {},  -- rest bar
    -- Bar 7
    {},  -- rest bar
    -- Bar 8
    {},  -- rest bar
    -- Bar 9
    { {pitch=-20,cells={11,14}}, {pitch=-18,cells={1,4}} },
    -- Bar 10
    { {pitch=-23,cells={10,11,14}}, {pitch=-22,cells={1,4,7}} },
    -- Bar 11
    { {pitch=-20,cells={11,14}}, {pitch=-18,cells={1,4}} },
    -- Bar 12
    { {pitch=-23,cells={10,11,14}}, {pitch=-22,cells={1,4}}, {pitch=-10,cells={7}} },
    -- Bar 13
    { {pitch=-23,cells={4}}, {pitch=-22,cells={1}}, {pitch=-18,cells={11,14}} },
    -- Bar 14
    { {pitch=-22,cells={10,11,14}}, {pitch=-15,cells={1,4,7}} },
    -- Bar 15
    { {pitch=-22,cells={1,4,11,14}} },
    -- Bar 16
    { {pitch=-18,cells={1,4,7}}, {pitch=-15,cells={10,11,14}} },
}

local function buildBeat()
    local buf = buffer.create(8192)
    local pos = 0

    local function writeU8(v)  buffer.writeu8(buf,  pos, v); pos = pos + 1 end
    local function writeI8(v)  buffer.writei8(buf,  pos, v); pos = pos + 1 end
    local function writeU16(v) buffer.writeu16(buf, pos, v); pos = pos + 2 end
    local function writeI16(v) buffer.writei16(buf, pos, v); pos = pos + 2 end
    local function writeStr(s)
        writeU16(#s)
        buffer.writestring(buf, pos, s, #s)
        pos = pos + #s
    end

    local BPM      = 84
    local CELLS    = 16
    local NUM_BARS = 16

    writeU8(18); writeU8(1); writeU8(0)
    writeStr("luciddreams")
    writeI16(BPM)
    writeU16(NUM_BARS)

    local function makeSeq(soundId, cells_list)
        local seq = {}
        for i = 1, CELLS do seq[i] = 0 end
        for _, c in ipairs(cells_list) do seq[c] = soundId end
        return seq
    end

    local function writeTrack(notes, pitch, volume)
        volume = volume or 100
        pitch  = pitch  or 0
        writeU8(0x03)
        writeU16(#notes)
        for _, n in ipairs(notes) do writeI16(n) end
        writeI8(volume)
        writeI8(pitch)
    end

    for barIdx = 1, NUM_BARS do
        local lead = melodyBars[barIdx] or {}
        local bass = bassBars[barIdx]   or {}

        local drumCount  = 3
        local trackCount = drumCount + #lead + #bass
        if trackCount == 0 then trackCount = 1 end

        writeU16(trackCount)

        if drumCount >= 3 then
            writeTrack(makeSeq(KICK_BASIC,     {1,5,9,13}),  0, 100)
            writeTrack(makeSeq(SNARE_CLEAN,    {5,13}),       0, 100)
            writeTrack(makeSeq(HIHAT_METALLIC, {3,7,11,15}), 0,  60)
        end

        for _, t in ipairs(lead) do
            writeTrack(makeSeq(MELODY_SAMPLE, t.cells), t.pitch, 100)
        end

        for _, t in ipairs(bass) do
            writeTrack(makeSeq(BASS_SAMPLE, t.cells), t.pitch, 100)
        end

        if trackCount == 1 and drumCount == 0 and #lead == 0 and #bass == 0 then
            writeTrack(makeSeq(0, {}))
        end

        writeI16(BPM)
        writeI8(CELLS)
    end

    local final = buffer.create(pos)
    buffer.copy(final, 0, buf, 0, pos)
    return final
end

local payload = buildBeat()
local remote  = ReplicatedStorage:WaitForChild("ZAP"):WaitForChild("ZAP_RELIABLE")
remote:FireServer(payload, {})

print("[luciddreams] Sent -- 16 bars @ 84 BPM.")
